CELL_SIZE = 20
BOARD_WIDTH = 800  # Multiple de CELL_SIZE
BOARD_HEIGHT = 400  # Multiple de CELL_SIZE
UI_WIDTH = 150  # Largeur de la zone d'interface utilisateur
WINDOW_WIDTH = BOARD_WIDTH + UI_WIDTH
WINDOW_HEIGHT = BOARD_HEIGHT
TITLE = 'Tower Defense'

TRACK_WIDTH = 2

ENEMY_RADIUS = 10
ENEMY_SPEED = 2

TOUR_RANGE = 50
ATTACK_DURATION = 500