name: Run tests with PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    uv-example:
        name: python
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: "pyproject.toml"

            - name: Install the project
              run: uv sync --locked --all-extras --dev

            - name: Run tests
              run: uv run pytest --junit-xml=test-results.xml --cov=src --cov-report=xml

            - name: Surface failing tests
              if: always()
              uses: pmeier/pytest-results-action@main
              with:
                path: test-results.xml
                summary: true
                display-options: fEX
                fail-on-empty: true
                title: Test results

            - name: Upload coverage report
              if: always()
              uses: codecov/codecov-action@v3
              with:
                files: coverage.xml
                flags: unittests
                name: codecov-coverage
                fail_ci_if_error: true
                verbose: true
              